# Generated by Django 5.2.2 on 2025-06-06 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='header',
            new_name='heading',
        ),
    ]
