# Generated by Django 5.2.2 on 2025-06-06 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_header_about_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='about',
            new_name='about_profile',
        ),
    ]
