# Generated by Django 5.2.2 on 2025-06-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_about_profile_about_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='portfolio_imgs/'),
        ),
    ]
