# Generated by Django 5.2.2 on 2025-06-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_home_picture_alter_portfolio_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='skills',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='link',
            field=models.URLField(max_length=20),
        ),
    ]
