# Generated by Django 5.2.2 on 2025-06-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_category_alter_portfolio_link_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='career',
            field=models.CharField(max_length=100),
        ),
    ]
